### ISSUE TITLE
One more TFBS database (HOCOMOCO)

### ISSUE THREAD

**Issue by VorontsovIE** [Danko-Lab/rtfbs_db#2]
Hello.
Please consider inclusion of motifs from the biggest and very well performing human&mouse motif database Hocomoco-10 (http://hocomoco.autosome.ru/). It contains motifs for 601 human TFs (and where possible these motifs are non-redundant).
On downloads page (http://hocomoco.autosome.ru/downloads) you can get motifs in several formats.
Hope you will find our database interesting and useful for your project.
Best, Ilya.

**Comment by ttriche** [comment]
or just import it from motifbreakR:
https://www.bioconductor.org/packages/release/bioc/vignettes/motifbreakR/inst/doc/motifbreakR-vignette.html#fn3

--t

**Comment by dankoc** [comment]
Thanks very much to both of you for the suggestions.  Hocomoco looks like quite a useful resource.  Based on a quick discussion, I expect we'll incorporate it in the next week or two.  We will leave the issue open until we're done.

We appreciate you pointing it out!

Best,
Charles

**Comment by VorontsovIE** [comment]
Thank you, Charles.
If any questions about HOCOMOCO will rise, don't hesitate to ask me.

Best, Ilya

**Comment by wzhy2000** [comment]
I just finished new version (v0.3.2),  which adds the functions to work with HOCOMOCO format  and MotifDb object. Thank you for your comment.
